//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="INaService.generated.cs">
//		Copyright(c)2016 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：Ecomm.Core.Service
//		生成时间：2016-12-09 09:33
// </copyright>
//------------------------------------------------------------------------------
using System;
using System.Linq;

using Quick.Framework.Tool;
using Ecomm.Core.Repository.Authen;
using Ecomm.Domain.Models.Authen;
using Ecomm.Site.Models.Authen.Na;
using System.Collections.Generic;
using Quick.Site.Common.Models;

namespace Ecomm.Core.Service.Authen
{
	/// <summary>
    /// 服务层接口 —— INaService
    /// </summary>
    public interface INaService
    {
		#region 属性

        IQueryable<Na> Nas { get; }

        #endregion

        #region 公共方法
        OperationResult Insert(NaModel model);

        OperationResult Update(NaModel model);

        /// <summary>
        /// 逻辑删除
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        OperationResult Delete(int Id);

        #endregion
	}
}
