//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="NaService.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：Ecomm.Core.Service
//		生成时间：2016-12-09 09:33
// </copyright>
//------------------------------------------------------------------------------


using System;
using System.ComponentModel.Composition;
using System.Linq;

using Quick.Framework.Tool;
using Ecomm.Domain.Models.Authen;
using Ecomm.Core.Repository.Authen;
using Ecomm.Site.Models.Authen.Na;
using System.Collections.Generic;
using Quick.Site.Common.Models;

namespace Ecomm.Core.Service.Authen.Impl
{
	/// <summary>
    /// 服务层实现 —— NaService
    /// </summary>
    [Export(typeof(INaService))]
    public class NaService : CoreServiceBase, INaService
    {
        #region 属性

        [Import]
        public INaRepository NaRepository { get; set; }

        public IQueryable<Na> Nas
        {
            get { return NaRepository.Entities; }
        }

        #endregion

        #region 公共方法

        public OperationResult Insert(NaModel model)
        {
            var entity = new Na
            {
                Name = model.Name,
            };
            NaRepository.Insert(entity);
            return new OperationResult(OperationResultType.Success, "添加成功");
        }

        public OperationResult Update(NaModel model)
        {
			var entity = Nas.First(t => t.Id == model.Id);
            entity.Name = model.Name;

            NaRepository.Update(entity);
            return new OperationResult(OperationResultType.Success, "更新成功");
        }

        public OperationResult Delete(int Id)
        {
            var model = Nas.FirstOrDefault(t => t.Id == Id);
            model.IsDeleted = true;

            NaRepository.Update(model);
            return new OperationResult(OperationResultType.Success, "删除成功");
        }

        #endregion
    }
}
